# Generated by Django 4.0.5 on 2022-06-08 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0002_alter_userpost_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dd5ab8mp3/image/upload/v1634659738/images/profile/user.jpg', max_length=255, verbose_name='image'),
        ),
    ]
