# Generated by Django 4.0.5 on 2022-06-08 23:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instaclone', '0004_alter_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/de7cwzlea/image/upload/v1654724662/o9qs85f1babplv1ke98t.jpg', max_length=255, verbose_name='image'),
        ),
    ]
